version: '1.0.0'
services:

  #Mongo db web client
  mongo-web-client:
    container_name: mongo-web-client
    image: mongo-express
    restart: always
    depends_on:
      - mongodb
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=35043
      - ME_CONFIG_MONGODB_SERVER=mongodb


  # Mongo Db server
  mongodb:
    container_name: mongo-db-6.0.2
    image: mongo:7.0.2
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=35043
    ports:
      - 27017:27017
    volumes:
      - ../data/mongodb:/data/db


